version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_system
      - SECRET_KEY=your-secret-key-here-change-in-production
      - SERVER_HOST=http://localhost:8000
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./backend/exports:/app/exports
    networks:
      - payment-network
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_system
    ports:
      - "5432:5432"
    networks:
      - payment-network
    restart: always

  # Uncomment for frontend when ready
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   networks:
  #     - payment-network
  #   restart: always

networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data: